

# ifndef __POLUART_H
# define __POLUART_H


# define QWLAN_UART_BASE	0x01233800

// -------------------------------------------------------------------
# define QWLAN_UART_UART_RBR_REG		(QWLAN_UART_BASE + 0x0)

# define QWLAN_UART_UART_RBR_VALUE_MASK		0xFF
# define QWLAN_UART_UART_RBR_VALUE_OFFSET		0x0
# define QWLAN_UART_UART_RBR_VALUE_DEFAULT		0x0
# define QWLAN_UART_UART_RBR_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_DLH_REG		(QWLAN_UART_BASE + 0x4)

# define QWLAN_UART_UART_DLH_VALUE_MASK		0xFF
# define QWLAN_UART_UART_DLH_VALUE_OFFSET		0x0
# define QWLAN_UART_UART_DLH_VALUE_DEFAULT		0x0
# define QWLAN_UART_UART_DLH_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_IIR_REG		(QWLAN_UART_BASE + 0x8)

# define QWLAN_UART_UART_IIR_FEN_MASK		0xC0
# define QWLAN_UART_UART_IIR_FEN_OFFSET		0x6
# define QWLAN_UART_UART_IIR_FEN_DEFAULT		0x0

# define QWLAN_UART_UART_IIR_ID_MASK		0xF
# define QWLAN_UART_UART_IIR_ID_OFFSET		0x0
# define QWLAN_UART_UART_IIR_ID_DEFAULT		0x0
# define QWLAN_UART_UART_IIR_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_LCR_REG		(QWLAN_UART_BASE + 0xC)

# define QWLAN_UART_UART_LCR_DLAB_MASK		0x80
# define QWLAN_UART_UART_LCR_DLAB_OFFSET		0x7
# define QWLAN_UART_UART_LCR_DLAB_DEFAULT		0x0

# define QWLAN_UART_UART_LCR_BREAK_MASK		0x40
# define QWLAN_UART_UART_LCR_BREAK_OFFSET		0x6
# define QWLAN_UART_UART_LCR_BREAK_DEFAULT		0x0

# define QWLAN_UART_UART_LCR_EPS_MASK		0x10
# define QWLAN_UART_UART_LCR_EPS_OFFSET		0x4
# define QWLAN_UART_UART_LCR_EPS_DEFAULT		0x0

# define QWLAN_UART_UART_LCR_PEN_MASK		0x8
# define QWLAN_UART_UART_LCR_PEN_OFFSET		0x3
# define QWLAN_UART_UART_LCR_PEN_DEFAULT		0x0

# define QWLAN_UART_UART_LCR_STOP_MASK		0x4
# define QWLAN_UART_UART_LCR_STOP_OFFSET		0x2
# define QWLAN_UART_UART_LCR_STOP_DEFAULT		0x0

# define QWLAN_UART_UART_LCR_DLS_MASK		0x3
# define QWLAN_UART_UART_LCR_DLS_OFFSET		0x0
# define QWLAN_UART_UART_LCR_DLS_DEFAULT		0x0
# define QWLAN_UART_UART_LCR_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_MCR_REG		(QWLAN_UART_BASE + 0x10)

# define QWLAN_UART_UART_MCR_AFCE_MASK		0x20
# define QWLAN_UART_UART_MCR_AFCE_OFFSET		0x5
# define QWLAN_UART_UART_MCR_AFCE_DEFAULT		0x0

# define QWLAN_UART_UART_MCR_LOOPBACK_MASK		0x10
# define QWLAN_UART_UART_MCR_LOOPBACK_OFFSET		0x4
# define QWLAN_UART_UART_MCR_LOOPBACK_DEFAULT		0x0

# define QWLAN_UART_UART_MCR_OUT2_MASK		0x8
# define QWLAN_UART_UART_MCR_OUT2_OFFSET		0x3
# define QWLAN_UART_UART_MCR_OUT2_DEFAULT		0x0

# define QWLAN_UART_UART_MCR_OUT1_MASK		0x4
# define QWLAN_UART_UART_MCR_OUT1_OFFSET		0x2
# define QWLAN_UART_UART_MCR_OUT1_DEFAULT		0x0

# define QWLAN_UART_UART_MCR_RTS_MASK		0x2
# define QWLAN_UART_UART_MCR_RTS_OFFSET		0x1
# define QWLAN_UART_UART_MCR_RTS_DEFAULT		0x0

# define QWLAN_UART_UART_MCR_DTR_MASK		0x1
# define QWLAN_UART_UART_MCR_DTR_OFFSET		0x0
# define QWLAN_UART_UART_MCR_DTR_DEFAULT		0x0
# define QWLAN_UART_UART_MCR_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_LSR_REG		(QWLAN_UART_BASE + 0x14)

# define QWLAN_UART_UART_LSR_RFE_MASK		0x80
# define QWLAN_UART_UART_LSR_RFE_OFFSET		0x7
# define QWLAN_UART_UART_LSR_RFE_DEFAULT		0x0

# define QWLAN_UART_UART_LSR_TEMPT_MASK		0x40
# define QWLAN_UART_UART_LSR_TEMPT_OFFSET		0x6
# define QWLAN_UART_UART_LSR_TEMPT_DEFAULT		0x40

# define QWLAN_UART_UART_LSR_THRE_MASK		0x20
# define QWLAN_UART_UART_LSR_THRE_OFFSET		0x5
# define QWLAN_UART_UART_LSR_THRE_DEFAULT		0x20

# define QWLAN_UART_UART_LSR_BI_MASK		0x10
# define QWLAN_UART_UART_LSR_BI_OFFSET		0x4
# define QWLAN_UART_UART_LSR_BI_DEFAULT		0x0

# define QWLAN_UART_UART_LSR_FE_MASK		0x8
# define QWLAN_UART_UART_LSR_FE_OFFSET		0x3
# define QWLAN_UART_UART_LSR_FE_DEFAULT		0x0

# define QWLAN_UART_UART_LSR_PE_MASK		0x4
# define QWLAN_UART_UART_LSR_PE_OFFSET		0x2
# define QWLAN_UART_UART_LSR_PE_DEFAULT		0x0

# define QWLAN_UART_UART_LSR_OE_MASK		0x2
# define QWLAN_UART_UART_LSR_OE_OFFSET		0x1
# define QWLAN_UART_UART_LSR_OE_DEFAULT		0x0

# define QWLAN_UART_UART_LSR_DR_MASK		0x1
# define QWLAN_UART_UART_LSR_DR_OFFSET		0x0
# define QWLAN_UART_UART_LSR_DR_DEFAULT		0x0
# define QWLAN_UART_UART_LSR_DEFAULT			0x60

// -------------------------------------------------------------------
# define QWLAN_UART_UART_MSR_REG		(QWLAN_UART_BASE + 0x18)

# define QWLAN_UART_UART_MSR_DCD_MASK		0x80
# define QWLAN_UART_UART_MSR_DCD_OFFSET		0x7
# define QWLAN_UART_UART_MSR_DCD_DEFAULT		0x0

# define QWLAN_UART_UART_MSR_RI_MASK		0x40
# define QWLAN_UART_UART_MSR_RI_OFFSET		0x6
# define QWLAN_UART_UART_MSR_RI_DEFAULT		0x0

# define QWLAN_UART_UART_MSR_DSR_MASK		0x20
# define QWLAN_UART_UART_MSR_DSR_OFFSET		0x5
# define QWLAN_UART_UART_MSR_DSR_DEFAULT		0x0

# define QWLAN_UART_UART_MSR_CTS_MASK		0x10
# define QWLAN_UART_UART_MSR_CTS_OFFSET		0x4
# define QWLAN_UART_UART_MSR_CTS_DEFAULT		0x10

# define QWLAN_UART_UART_MSR_DDCD_MASK		0x8
# define QWLAN_UART_UART_MSR_DDCD_OFFSET		0x3
# define QWLAN_UART_UART_MSR_DDCD_DEFAULT		0x0

# define QWLAN_UART_UART_MSR_TERI_MASK		0x4
# define QWLAN_UART_UART_MSR_TERI_OFFSET		0x2
# define QWLAN_UART_UART_MSR_TERI_DEFAULT		0x0

# define QWLAN_UART_UART_MSR_DDSR_MASK		0x2
# define QWLAN_UART_UART_MSR_DDSR_OFFSET		0x1
# define QWLAN_UART_UART_MSR_DDSR_DEFAULT		0x0

# define QWLAN_UART_UART_MSR_DCTS_MASK		0x1
# define QWLAN_UART_UART_MSR_DCTS_OFFSET		0x0
# define QWLAN_UART_UART_MSR_DCTS_DEFAULT		0x1
# define QWLAN_UART_UART_MSR_DEFAULT			0x11

// -------------------------------------------------------------------
# define QWLAN_UART_UART_SCRATCH_REG		(QWLAN_UART_BASE + 0x1C)

# define QWLAN_UART_UART_SCRATCH_SCRATCH_MASK		0xFF
# define QWLAN_UART_UART_SCRATCH_SCRATCH_OFFSET		0x0
# define QWLAN_UART_UART_SCRATCH_SCRATCH_DEFAULT		0x0
# define QWLAN_UART_UART_SCRATCH_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_FAR_REG		(QWLAN_UART_BASE + 0x70)

# define QWLAN_UART_UART_FAR_FAR_MASK		0x1
# define QWLAN_UART_UART_FAR_FAR_OFFSET		0x0
# define QWLAN_UART_UART_FAR_FAR_DEFAULT		0x0
# define QWLAN_UART_UART_FAR_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_USR_REG		(QWLAN_UART_BASE + 0x7C)

# define QWLAN_UART_UART_USR_BUSY_MASK		0x1
# define QWLAN_UART_UART_USR_BUSY_OFFSET		0x0
# define QWLAN_UART_UART_USR_BUSY_DEFAULT		0x0
# define QWLAN_UART_UART_USR_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_HTX_REG		(QWLAN_UART_BASE + 0xA4)

# define QWLAN_UART_UART_HTX_HALT_MASK		0x1
# define QWLAN_UART_UART_HTX_HALT_OFFSET		0x0
# define QWLAN_UART_UART_HTX_HALT_DEFAULT		0x0
# define QWLAN_UART_UART_HTX_DEFAULT			0x0

// -------------------------------------------------------------------
# define QWLAN_UART_UART_DMASA_REG		(QWLAN_UART_BASE + 0xA8)

# define QWLAN_UART_UART_DMASA_ACK_MASK		0x1
# define QWLAN_UART_UART_DMASA_ACK_OFFSET		0x0
# define QWLAN_UART_UART_DMASA_ACK_DEFAULT		0x0
# define QWLAN_UART_UART_DMASA_DEFAULT			0x0
#endif
